kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mosquitto-operator-binding
subjects:
- kind: ServiceAccount
  name: mosquitto-operator
roleRef:
  kind: ClusterRole
  name: mosquitto-operator
  apiGroup: rbac.authorization.k8s.io
