apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mosquitto-operator
  template:
    metadata:
      labels:
        name: mosquitto-operator
    spec:
      serviceAccountName: mosquitto-operator
      containers:
        - name: mosquitto-operator
          # Replace this with the built image name
          image: 192.168.1.99/library/mosquitto-operator:0.0.1
          command:
          - mosquitto-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "mosquitto-operator"
